site_name: stlib-ext

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md

  - moretyping:
    - Home: moretyping/index.md
    - Data:
        - Overview: moretyping/data/index.md
        - moretyping.data:
            - Number: moretyping/data/number.md

    - Visualise:
        - Overview: moretyping/visualise/index.md
        - moretyping.vis:
            - VisLink: moretyping/visualise/vis-link.md
            - ViewJSON: moretyping/visualise/view-json.md

  - morefunctools:
    - Home: morefunctools/index.md
    - API:
      - morefunctools.experimental: morefunctools/experimental.md